name: Test
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          MONGODB_USERNAME: ${{ MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ MONGODB_PASSWORD }}
          MONGODB_DATABASE: ${{ MONGODB_DATABASE }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: |
      touch .env
      MONGODB_USERNAME: ${{ MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ MONGODB_PASSWORD }}
      MONGODB_DATABASE: ${{ MONGODB_DATABASE }} >> .env
        npm run test-ci
